name: Compile 和 Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 下载安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install gcc python3
          pip3 install pandas

      - name: 编译main.c
        run: |
          gcc main.c -o main.out

      - name: 下载py测试脚本
        run: |
          git clone https://github.com/NGC2237plus/c-cpp_test.git
          cp c-cpp_test/test.py .

      - name: Set Git user
        run: |
          git config --global user.email "star32349@outlook.com"
          git config --global user.name "NGC2237plus"
      
      - name: 运行测试
        run: |
          python3 test.py

