name: 评测

on:
  push:
    branches:
      - main
    paths:
      - main.c  # 仅在 main.c 被修改时触发

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GIT_TOKEN: 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
    steps:
      - name: 检出仓库
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install gcc python3
          pip3 install pandas

      - name: 下载py测试脚本
        run: |
          git clone https://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@github.com/Firefly-fly/c-cpp_test.git
          cp c-cpp_test/test.py .

      - name: 运行测试
        run: |
          python3 test.py
